### ISSUE TITLE
NoMethodError in LiteCable::Server::Base#each_frame

### ISSUE THREAD

**Issue by cyberarm** [palkan/litecable#74]
### Tell us about your environment

**Ruby version:** ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]

**`litecable` gem version:** 0.8.1

```txt
#<Thread:0x00007f283405b870 /home/cyberarm/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/litecable-0.8.1/lib/lite_cable/server/client_socket/base.rb:69 run> terminated with exception (report_on_exception is true):
E, [2024-04-14T02:14:15.375827 #1066840] ERROR -- LiteCable: Socket send failed: Broken pipe
/home/cyberarm/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/litecable-0.8.1/lib/lite_cable/server/client_socket/base.rb:140:in `each_frame': undefined method `empty?' for nil (NoMethodError)

            break if data.empty?
                         ^^^^^^^
        from /home/cyberarm/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/litecable-0.8.1/lib/lite_cable/server/client_socket/base.rb:73:in `block in listen'
```

https://github.com/palkan/litecable/blob/77557c67846ffe8ac4b9248dd1e291ae95b399db/lib/lite_cable/server/client_socket/base.rb#L135-L155

**Comment by palkan** [comment]
Looks like a recent change in Ruby: https://bugs.ruby-lang.org/issues/19012

Now `#recv` returns `nil`.  Fixed and to be released in 0.8.2.
